# Site settings
title: viziotherapy
header-img: img/home-bg-perm2.jpg
email: raghavj1991@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/viziotherapy"
url: "confusedsouls.github.io"
twitter_username: raghavistic
github_username:  confusedsouls
facebook_username:  raghavj1991

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
